dotnet/src/Bnbooking.WWW/Areas/Backoffice/Controllers/BedTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Bnbooking.Db;
using Bnbooking.Models;
using Bnbooking.Models.Security;
using Bnbooking.Models.Utilities;
using Bnbooking.Models.ViewModels;

namespace Bnbooking.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class BedTypeController : BaseController 
    {
        public BedTypeController(ApplicationDbContext applicationDbContext):base(applicationDbContext)
        {
        }

        public async Task<IActionResult> Index() 
        {
            var model = await ApplicationDbContext.BedTypes.OrderBy(o => o.Name).ToListAsync();

            if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest") 
            {
                return PartialView("_ListPartial", model);
            }
            
            return View(model);

        }

        [HttpGet]
        public IActionResult Create() 
        {
            var model = new BedType();

            return View(model);
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BedType model)
        {
            var alert = new Alert();
            try
            {
                if(!ModelState.IsValid) {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }
                    
                
                ApplicationDbContext.BedTypes.Add(model);
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.CREATENOK;
                    throw new Exception();
                }   

                alert.Message = ApplicationDbContextMessage.CREATEOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Int64? id)
        { 
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            
            var model = await ApplicationDbContext.BedTypes.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BedType model)
        {
            var alert = new Alert();
            try 
            {
                if(!ModelState.IsValid)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }   
                    
                var originalModel = ApplicationDbContext.BedTypes.FirstOrDefault(m => m.Id == model.Id);
                
                if(originalModel == null) 
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }
                    
                originalModel.Name = model.Name;
                originalModel.Description = model.Description;
                
                ApplicationDbContext.BedTypes.Attach(originalModel);
                ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.EDITNOK;
                    throw new Exception();
                } 
                
                alert.Message = ApplicationDbContextMessage.EDITOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }

        [HttpGet("[area]/[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Delete(Int64 id, [FromQuery] ActionType actionType)
        {
            var model = await ApplicationDbContext.BedTypes.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            var viewModel = new ActionBedTypeViewModel()
            {
                BaseEntity = model,
                ActionType = actionType
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ActionBedTypeViewModel model)
        {
            var alert = new Alert();// Alert
            try
            {
                var originalModel = ApplicationDbContext.BedTypes.FirstOrDefault(m => m.Id == model.BaseEntity.Id);
                
                if(originalModel == null)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                switch(model.ActionType)
                {
                    case ActionType.Delete:
                        alert.Message = ApplicationDbContextMessage.DELETEOK;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Deleted;
                        break;
                    case ActionType.SoftDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTDELETEOK;
                        originalModel.DeletedAt = DateTime.Now;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                    case ActionType.SoftUnDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTUNDELETEOK;
                        originalModel.DeletedAt = (Nullable<DateTime>)null;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                }

                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {                   
                    switch(model.ActionType)
                    {
                        case ActionType.Delete:
                            alert.Message = ApplicationDbContextMessage.DELETENOK;
                            break;
                        case ActionType.SoftDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTDELETENOK;
                            break;
                        case ActionType.SoftUnDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTUNDELETENOK;
                            break;
                    }
                    throw new Exception();
                } 

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/BedType/Create.cshtml
@model Bnbooking.Models.BedType
@{
    ViewBag.Title = "BedType Management";
    ViewBag.SubTitle = "Manage all your groups via this platform";
    ViewBag.Description = "Create an BedTypes via the form or got back to the list of BedTypes ...";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="bnb-card">
    <h2 class="title">Create a BedType</h2>
          <div class="form-holder">
            <form asp-controller="BedType" asp-action="Create" method="post" asp-antiforgery="true">
                    <label asp-for="Name">Name</label>
                    <input class="input-field" asp-for="Name">

                    <label asp-for="Description">Description</label>
                    <input class="input-field" asp-for="Description">

                <button type="submit" class="waves-effect waves-light btn">Create</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/BedType/Delete.cshtml
@model Bnbooking.Models.ViewModels.ActionBedTypeViewModel
@{
    ViewBag.Title = "BedType Management";
    ViewBag.SubTitle = "Manage all the BedTypes on your SAAS platform";
    ViewBag.Description = "Create an BedType via the form or go back to the list of BedTypes.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="bnb-card">
            <h2 class="title">Delete an existing BedType</h2>
          <div class="form-holder">
            <p>Do you wish to @Model.Action the BedType @Model.BaseEntity.Name?</p>
            <form asp-controller="BedType" asp-action="Delete" method="post" asp-antiforgery="true">
                <input asp-for="BaseEntity.Id" type="hidden">
                <input asp-for="BaseEntity.Name" type="hidden">
                <input asp-for="BaseEntity.Description" type="hidden">
                <input asp-for="ActionType" type="hidden">
                <button type="submit" class="waves-effect waves-light btn">@Model.Action</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/BedType/Edit.cshtml
@model Bnbooking.Models.BedType
@{
    ViewBag.Title = "BedType Management";
    ViewBag.SubTitle = "Manage all the BedTypes on your SAAS platform";
    ViewBag.Description = "Edit an existing BedType via the form or go back to the list of BedTypes.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
        <div class="bnb-card">
            <h2 class="title">Edit an existing BedType</h2>
          <div class="form-holder">
            <form asp-controller="BedType" asp-action="Edit" method="post" asp-antiforgery="true">
                <input asp-for="Id" type="hidden">
                    <label asp-for="Name">Name</label>
                    <input class="input-field" asp-for="Name">

                    <label asp-for="Description">Description</label>
                    <input class="input-field" asp-for="Description">        

                <button type="submit" class="waves-effect waves-light btn">Save</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/BedType/Index.cshtml
@model ICollection<Bnbooking.Models.BedType>
@{
    ViewBag.Title = "Bed Type Management";
    ViewBag.SubTitle = "Manage all your bedtypes via this platform";
    ViewBag.Description = "Select a bedtype to edit ...";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
   <div class="bnb-card">
        <h2 class="title">List of bed types</h2>       
        @Html.Partial("_ListPartial", @Model)
    </div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/BedType/_ListPartial.cshtml
@model ICollection<Bnbooking.Models.BedType>
@Html.AntiForgeryToken()
@if (Model != null && Model.Count() > 0)
{
      <table class="striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @foreach (var bedtype in Model)
          {
            <tr data-id="bedtype-@bedtype.Id">
              <td>@bedtype.Name</td>
              <td>@bedtype.Description</td>
              <td>@bedtype.CreatedAt</td>
              <td>
                <a asp-controller="BedType" asp-action="Edit" asp-route-id="@bedtype.Id">
                  <i class="material-icons" role="presentation">edit</i>
                </a>
                @if (@bedtype.DeletedAt != null)
                {
                    <a asp-controller="BedType" asp-action="Delete" asp-route-id="@bedtype.Id" asp-route-actionType="5" data-is-softdelete="true">
                      <i class="material-icons" role="presentation">delete</i>
                    </a>
                }
                else
                {
                    <a asp-controller="BedType" asp-action="Delete" asp-route-id="@bedtype.Id" asp-route-actionType="4">
                      <i class="material-icons" role="presentation">delete</i>
                    </a>
                }
                <a asp-controller="BedType" asp-action="Delete" asp-route-id="@bedtype.Id" asp-route-actionType="3">
                  <i class="material-icons" role="presentation">delete_forever</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
      </table>
}
else
{
    <p>No Bedtypes in the database!</p>
}
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/BedType/_QuickActionsPartial.cshtml
<div class="card blue-grey darken-1">
    <div class="card-content white-text">
        <span class="card-title">Overview</span>
        <p>@ViewBag.Description</p>
    </div>
    <div class="card-action">
        <a asp-controller="BedType" asp-action="Index"><i class="material-icons">list</i><span>List of items</span></a>
        <a asp-controller="BedType" asp-action="Create"><i class="material-icons">add</i><span>Create a new item</span></a>
    </div>
    </div>
</div>