dotnet/src/Bnbooking.WWW/Areas/Backoffice/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Bnbooking.Db;
using Bnbooking.Models;
using Bnbooking.Models.Security;
using Bnbooking.Models.Utilities;
using Bnbooking.Models.ViewModels;

namespace Bnbooking.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class ServiceController : BaseController 
    {
        public ServiceController(ApplicationDbContext applicationDbContext):base(applicationDbContext)
        {
        }

        public async Task<IActionResult> Index(string sortParam, string searchString) 
        {
            List<Service> services = null;
            
            if(!String.IsNullOrEmpty(searchString))
            {
                services = await ApplicationDbContext.Services.Where(o => o.Name.Contains(searchString)).OrderByDescending(o => o.CreatedAt).ToListAsync();
            }
            else
            {
                services = await ApplicationDbContext.Services.OrderByDescending(o => o.CreatedAt).ToListAsync();
            }

            ViewBag.NameSortParam = "name_asc";
            ViewBag.DescriptionSortParam = "description_asc";

           // var model = await ApplicationDbContext.Services.OrderBy(o => o.Name).ToListAsync();
        if(String.IsNullOrEmpty(sortParam))
            {
                services = services.OrderByDescending(o => o.CreatedAt).ToList();
            }
            else
            {
                switch(sortParam)
                {
                    case "name_asc":
                        ViewBag.NameSortParam = "name_desc";
                        services = services.OrderBy(o => o.Name).ToList();
                        break;
                    case "name_desc":
                        ViewBag.NameSortParam = "name_asc";
                        services = services.OrderByDescending(o => o.Name).ToList();
                        break;
                    case "description_asc":
                        ViewBag.DescriptionSortParam = "description_desc";
                        services = services.OrderBy(o => o.Description).ToList();
                        break;
                    case "description_desc":
                        ViewBag.DescriptionSortParam = "description_asc";
                        services = services.OrderByDescending(o => o.Description).ToList();
                        break;
                }
            }
            if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest") 
            {
                return PartialView("_ListPartial", services);
            }
            
            return View(services);

        }

        [HttpGet]
        public IActionResult Create() 
        {
            var model = new Service();

            return View(model);
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Service model)
        {
            var alert = new Alert();
            try
            {
                if(!ModelState.IsValid) {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }
                    
                
                ApplicationDbContext.Services.Add(model);
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.CREATENOK;
                    throw new Exception();
                }   

                alert.Message = ApplicationDbContextMessage.CREATEOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(Int64? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            
            var model = await ApplicationDbContext.Services.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Service model)
        {
            var alert = new Alert();
            try 
            {
                if(!ModelState.IsValid)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.INVALID;
                    throw new Exception();
                }   
                    
                var originalModel = ApplicationDbContext.Services.FirstOrDefault(m => m.Id == model.Id);
                
                if(originalModel == null) 
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }
                    
                originalModel.Name = model.Name;
                originalModel.Description = model.Description;
                
                ApplicationDbContext.Services.Attach(originalModel);
                ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.EDITNOK;
                    throw new Exception();
                } 
                
                alert.Message = ApplicationDbContextMessage.EDITOK;
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                ModelState.AddModelError(string.Empty, alert.ExceptionMessage);
            }
            return View(model);
        }

        [HttpGet("[area]/[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Delete(Int64 id, [FromQuery] ActionType actionType)
        {
            var model = await ApplicationDbContext.Services.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }
            
            var viewModel = new ActionServiceViewModel()
            {
                BaseEntity = model,
                ActionType = actionType
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(ActionServiceViewModel model)
        {
            var alert = new Alert();// Alert
            try
            {
                var originalModel = ApplicationDbContext.Services.FirstOrDefault(m => m.Id == model.BaseEntity.Id);
                
                if(originalModel == null)
                {
                    alert.Message = alert.ExceptionMessage = ApplicationDbContextMessage.NOTEXISTS;
                    throw new Exception();
                }

                switch(model.ActionType)
                {
                    case ActionType.Delete:
                        alert.Message = ApplicationDbContextMessage.DELETEOK;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Deleted;
                        break;
                    case ActionType.SoftDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTDELETEOK;
                        originalModel.DeletedAt = DateTime.Now;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                    case ActionType.SoftUnDelete:
                        alert.Message = ApplicationDbContextMessage.SOFTUNDELETEOK;
                        originalModel.DeletedAt = (Nullable<DateTime>)null;
                        ApplicationDbContext.Entry(originalModel).State = EntityState.Modified;
                        break;
                }

                
                if (await ApplicationDbContext.SaveChangesAsync() == 0)
                {                   
                    switch(model.ActionType)
                    {
                        case ActionType.Delete:
                            alert.Message = ApplicationDbContextMessage.DELETENOK;
                            break;
                        case ActionType.SoftDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTDELETENOK;
                            break;
                        case ActionType.SoftUnDelete:
                            alert.Message = ApplicationDbContextMessage.SOFTUNDELETENOK;
                            break;
                    }
                    throw new Exception();
                } 

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                alert.Type = AlertType.Error;
                alert.ExceptionMessage = ex.Message;

                if (this.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return Json(alert);
                }
                else
                {
                    return RedirectToAction("Index");

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/Service/Create.cshtml
@model Bnbooking.Models.Service
@{
    ViewBag.Title = "Service Management";
    ViewBag.SubTitle = "Manage all your groups via this platform";
    ViewBag.Description = "Create an services via the form or got back to the list of services ...";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="bnb-card">
    <h2 class="title">Create a Service</h2>
          <div class="form-holder">
            <form asp-controller="Service" asp-action="Create" method="post" asp-antiforgery="true">
                <label asp-for="Name">Name</label>
                <input class="input-field" asp-for="Name">
                
                <input class="input-field" asp-for="Description">
                <label asp-for="Description">Description</label>

                <button type="submit" class="waves-effect waves-light btn">Create</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/Service/Delete.cshtml
@model Bnbooking.Models.ViewModels.ActionServiceViewModel
@{
    ViewBag.Title = "Service Management";
    ViewBag.SubTitle = "Manage all the Services on your SAAS platform";
    ViewBag.Description = "Create an Service via the form or go back to the list of Services.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
<div class="bnb-card">
            <h2 class="title">Delete an existing Service</h2>
          <div class="form-holder">
            <p>Do you wish to @Model.Action the Service @Model.BaseEntity.Name?</p>
            <form asp-controller="Service" asp-action="Delete" method="post" asp-antiforgery="true">
                <input asp-for="BaseEntity.Id" type="hidden">
                <input asp-for="BaseEntity.Name" type="hidden">
                <input asp-for="BaseEntity.Description" type="hidden">
                <input asp-for="ActionType" type="hidden">
                <button type="submit" class="waves-effect waves-light btn">@Model.Action</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/Service/Edit.cshtml
@model Bnbooking.Models.Service
@{
    ViewBag.Title = "Service Management";
    ViewBag.SubTitle = "Manage all the Services on your SAAS platform";
    ViewBag.Description = "Edit an existing Service via the form or go back to the list of Services.";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
        <div class="bnb-card">
            <h2 class="title">Edit an existing Service</h2>
          <div class="form-holder">
            <form asp-controller="Service" asp-action="Edit" method="post" asp-antiforgery="true">
                <input asp-for="Id" type="hidden">
                    <label asp-for="Name">Name</label>
                    <input class="input-field" asp-for="Name">
                    
                    <label asp-for="Description">Description</label>
                    <input class="input-field" asp-for="Description">
                    
                <button type="submit" class="waves-effect waves-light btn">Save</button>
            </form>
          </div>
        </div>
    </div>
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/Service/Index.cshtml
@model ICollection<Bnbooking.Models.Service>
@{
    ViewBag.Title = "Service Management";
    ViewBag.SubTitle = "Manage all the Services on your SAAS platform";
    ViewBag.Description = "Select a Service to edit or select multiple Services to do export functions or mass asignment to them";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
<div class="overview">
    @Html.Partial("_QuickActionsPartial")
</div>
    <div class="bnb-card">
        <h2 class="title">List of Services</h2>       
        @Html.Partial("_ListPartial", @Model)
    </div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/Service/_ListPartial.cshtml
@model ICollection<Bnbooking.Models.Service>
@Html.AntiForgeryToken()
		@if (Model != null && Model.Count() > 0)
		{
       <form asp-controller="service" asp-action="Index" method="get">
        <div class="row">
          <div class="col s3">
            <input class="input-field " type="text" name="searchString" id="searchString" placeholder="Search...">
          </div>
          <button type="submit" class="waves-effect waves-light btn">Search</button>
        </div>
      </form>
      <table class="striped"> 
        <thead>
          <tr>
            <th><a asp-controller="service" asp-action="Index" asp-route-sortParam="@ViewBag.NameSortParam">Name</a></th>
            <th><a asp-controller="service" asp-action="Index" asp-route-sortParam="@ViewBag.DescriptionSortParam">Description</a></th>
            <th>Created</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
           @foreach (var service in Model)
          {
            <tr data-id="service-@service.Id">
              <td>@service.Name</td>
              <td>@service.Description</td>
              <td>@service.CreatedAt</td>
              <td>
                <a asp-controller="service" asp-action="Edit" asp-route-id="@service.Id">
                  <i class="material-icons" role="presentation">edit</i>
                </a>
                @if (@service.DeletedAt != null)
                {
                    <a asp-controller="service" asp-action="Delete" asp-route-id="@service.Id" asp-route-actionType="5" data-is-softdelete="true">
                      <i class="material-icons" role="presentation">delete</i>
                    </a>
                }
                else
                {
                    <a asp-controller="service" asp-action="Delete" asp-route-id="@service.Id" asp-route-actionType="4">
                      <i class="material-icons" role="presentation">delete</i>
                    </a>
                }
                <a asp-controller="service" asp-action="Delete" asp-route-id="@service.Id" asp-route-actionType="3">
                  <i class="material-icons" role="presentation">delete_forever</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
      </table>
      }
      else
      {
          <p>No Services in the database!</p>
      }
</div>

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/Service/_QuickActionsPartial.cshtml
<div class="card blue-grey darken-1">
    <div class="card-content white-text">
        <span class="card-title">Overview</span>
        <p>@ViewBag.Description</p>
    </div>
    <div class="card-action">
        <a asp-controller="Service" asp-action="Index"><i class="material-icons">list</i><span>List of items</span></a>
        <a asp-controller="Service" asp-action="Create"><i class="material-icons">add</i><span>Create a new item</span></a>
    </div>
    </div>
</div>