dotnet/src/Bnbooking.WWW/Areas/Backoffice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Bnbooking.Db;
using Bnbooking.Models;
using Bnbooking.Models.Security;

namespace  Bnbooking.WWW.Areas.Backoffice.Controllers 
{
    [Area("Backoffice")]
    public class HomeController : BaseController 
    {
        public HomeController():base()
        {
        }

        public IActionResult Index() 
        {
            return View();
        }
    }
}

dotnet/src/Bnbooking.WWW/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Bnbooking.Db;
using Bnbooking.Models;
using Bnbooking.Models.Security;
using Bnbooking.Models.Utilities;
namespace Bnbooking.Controllers 
{
    public class HomeController : BaseController
    {
        public HomeController(ApplicationDbContext applicationDbContext):base(applicationDbContext) 
        {
        }
       
        public async Task<IActionResult> Index()
        {
            var model = await ApplicationDbContext.Cities.OrderBy(o => o.Name).ToListAsync();         

            return View(model);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            
            return View("Contact");
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

dotnet/src/Bnbooking.WWW/Controllers/PlaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Bnbooking.Db;
using Bnbooking.Models;
using Bnbooking.Models.Security;
using Bnbooking.Models.Utilities;
using Bnbooking.Models.ViewModels;

namespace Bnbooking.Controllers 
{

    public class PlaceController : BaseController
    {
        public PlaceController(ApplicationDbContext applicationDbContext):base(applicationDbContext) 
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index(Int32? id) 
        {
            var model = await ApplicationDbContext.Places.OrderBy(o => o.Name).Include(c => c.City).ToListAsync();      
            if (id == null)
            {               
               return View(model); 
            }   else
            {      
                           
                model = await ApplicationDbContext.Places.OrderBy(o => o.Name).Where(p => p.CityId == id).Include(c => c.City).ToListAsync();  
                ViewBag.title = "id"; 
                return View(model);
            }

            
        }
        
        [HttpGet]
        public async Task<IActionResult> Detail(Int32? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            
            var model = await ApplicationDbContext.Places.FirstOrDefaultAsync(m => m.Id == id);
            
            if(model == null)
            {
                return RedirectToAction("Index");
            }

            var viewModel = await ViewModel(model);
            
            return View(viewModel);
        }
        private async Task<PlaceDetailViewModel> ViewModel(Place Place = null) 
        {
            var Cities = await ApplicationDbContext.Cities.Select(o => new SelectListItem { 
                Value = o.Id.ToString(), 
                Text = o.Name 
            }).ToListAsync();
            var HouseTypes = await ApplicationDbContext.HouseTypes.Select(o => new SelectListItem { 
                Value = o.Id.ToString(), 
                Text = o.Name 
            }).ToListAsync();
            var RentalTypes = await ApplicationDbContext.RentalTypes.Select(o => new SelectListItem { 
                Value = o.Id.ToString(), 
                Text = o.Name 
            }).ToListAsync();
             var CancelTypes = await ApplicationDbContext.CancelTypes.Select(o => new SelectListItem { 
                Value = o.Id.ToString(), 
                Text = o.Name 
            }).ToListAsync();
            var BedTypes = await ApplicationDbContext.BedTypes.Select(o => new SelectListItem { 
                Value = o.Id.ToString(), 
                Text = o.Name 
            }).ToListAsync();

            
            var bedTypes = await ApplicationDbContext.BedTypes.ToListAsync();
            var viewModel = new PlaceDetailViewModel 
            {
                Place = (Place != null)?Place:new Place(),
                Cities = Cities,
                HouseTypes = HouseTypes,
                BedTypes = new MultiSelectList(bedTypes, "Id", "Name"),
                RentalTypes = RentalTypes,
                CancelTypes = CancelTypes
            };

            return viewModel;
        }

    }

}

dotnet/src/Bnbooking.WWW/Areas/Backoffice/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    ViewBag.SubTitle = "Overview and statistics";
    ViewBag.Description = "Dashboard overview and statistics";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}
</div> <!-- closing de header div (to use whole container -->
        <div class="row">
            <div class="col s4">
                <div class="card pink darken-4">
                    <a asp-controller="Place" asp-action="Index">
                        <div class="card-content white-text">
                            <span class="card-title">@await Component.InvokeAsync("AmountForEntity", new { entityType = "Place"})</span>
                        </div>
                    </a>
                    <div class="card-action">
                        <a asp-controller="Place" asp-action="Index">View all</a>
                    </div>
                </div>
            </div>
            <div class="col s4">
                <div class="card blue darken-2">
                    <a asp-controller="City" asp-action="Index">
                        <div class="card-content white-text">
                            <span class="card-title">@await Component.InvokeAsync("AmountForEntity", new { entityType = "City"})
                        </div>
                    </a>    
                    <div class="card-action">
                        <a asp-controller="City" asp-action="Index">View all</a>
                    </div>
                </div>
            </div>
            <div class="col s4">
                <div class="card green darken-1">
                    <a asp-controller="Service" asp-action="Index">
                        <div class="card-content white-text">
                            <span class="card-title">@await Component.InvokeAsync("AmountForEntity", new { entityType = "Service"})</span>
                        </div>
                    </a>
                    <div class="card-action">
                        <a asp-controller="Service" asp-action="Index">View all</a>
                    </div>
                </div>
            </div>
            <div class="col s4">
                <div class="card red darken-1">
                    <a asp-controller="Person" asp-action="Index">
                        <div class="card-content white-text">
                            <span class="card-title">@await Component.InvokeAsync("AmountForEntity", new { entityType = "Person"})</span>
                        </div>
                    </a>
                    <div class="card-action">
                        <a asp-controller="Person" asp-action="Index">View all</a>
                    </div>
                </div>
            </div>
            <div class="col s4">
                <div class="card brown darken-1">
                    <a asp-controller="BedType" asp-action="Index">
                        <div class="card-content white-text">
                            <span class="card-title">@await Component.InvokeAsync("AmountForEntity", new { entityType = "BedType"})</span>
                        </div>
                    </a>
                    <div class="card-action">
                        <a asp-controller="BedType" asp-action="Index">View all</a>
                    </div>
                </div>
            </div>
            <div class="col s4">
                <div class="card  red darken-4">
                    <a asp-controller="Discount" asp-action="Index">
                        <div class="card-content white-text">
                            <span class="card-title">@await Component.InvokeAsync("AmountForEntity", new { entityType = "Discount"})</span>
                        </div>
                    </a>
                    <div class="card-action">
                        <a asp-controller="Discount" asp-action="Index">View all</a>
                    </div>
                </div>
            </div>
            <div class="col s4">
                <div class="card deep-purple darken-3">
                    <a asp-controller="Discount" asp-action="Index">
                        <div class="card-content white-text">
                            <span class="card-title">@await Component.InvokeAsync("AmountForEntity", new { entityType = "CancelType"})</span>
                        </div>
                    </a>
                    <div class="card-action">
                        <a asp-controller="CancelType" asp-action="Index">View all</a>
                    </div>
                </div>
            </div>
        </div>
  